- LICENSE
- _quarto.yml
- about.md
- index.md
Thanks for this excellent input @colliand!
> Apply feedback from James

- _quarto.yml
---
:mag: Preview: https://geojupyter--11.org.readthedocs.build/en/11/
> Disclaim relationship with Project Jupyter

- about.md
---
:mag: Preview: https://geojupyter--13.org.readthedocs.build/en/13/
> Add BIDs to collaborators

- _quarto.yml
- blog/index.md
---
:mag: Preview: https://geojupyter--16.org.readthedocs.build/en/16/
> Add RSS feed for blog posts

- .github/workflows/meeting-notes.yml
---
:mag: Preview: https://geojupyter--19.org.readthedocs.build/en/19/
> Fix schema error in meeting notes workflow

- .github/workflows/meeting-notes.yml
---
:mag: Preview: https://geojupyter--20.org.readthedocs.build/en/20/
> Fixup workflow variable interpolation

- .github/workflows/meeting-notes.yml
---
:mag: Preview: https://geojupyter--22.org.readthedocs.build/en/22/
> Fixup meeting notes workflow condition

- .github/meeting-notes-templates/core.md
- .github/meeting-notes-templates/virtual-hackathon.md
- .github/workflows/meeting-notes.yml
---
:mag: Preview: https://geojupyter--29.org.readthedocs.build/en/29/
> Enrich meeting notes templates

- .github/meeting-notes-templates/virtual-hackathon.md
---
:mag: Preview: https://geojupyter--31.org.readthedocs.build/en/31/
> Clarify the hack teams section of virtual hackathon notes template

- README.md
---
:mag: Preview: https://geojupyter--33.org.readthedocs.build/en/33/
> Add meeting notes instruction to README

- about.md
- blog/20250129-announcing-geojupyter-hackathons/index.md
- call-to-action.md
- index.md
---
:mag: Preview: https://geojupyter--35.org.readthedocs.build/en/35/
> Update project status, hackathon blog post, call to action

- .github/meeting-notes-templates/virtual-hackathon.md
---
:mag: Preview: https://geojupyter--37.org.readthedocs.build/en/37/
> Add lightning demo to hackathon notes template

- .github/meeting-notes-templates/jupytergis-sync.md
- .github/workflows/meeting-notes.yml
@martinRenou Check the final paragraph of the README for usage instructions!
---
:mag: Preview: https://geojupyter--42.org.readthedocs.build/en/42/
> Add action and template for JupyterGIS sync meetings

- .github/meeting-notes-templates/virtual-hackathon.md
Converted lazy numbered list to an explicit numbered list in the virtual hackathon meeting notes .md. 
Resolves #46.
---
:mag: Preview: https://geojupyter--50.org.readthedocs.build/en/50/
> Converted lazy numbered list to an explicit numbered list

- blog/20250225-jupytergis-sync/index.md
---
:mag: Preview: https://geojupyter--56.org.readthedocs.build/en/56/
> Fix callout in Feb 25 JGIS sync meeting notes

- blog/20250410-community-insight-qgis-bounce/index.md
@lucialayr thanks so much for your feedback on this! I made some changes per your suggestions, what do you think?
---
:mag: Preview: https://geojupyter--68.org.readthedocs.build/en/68/
> Update "QGIS Bounce" blog post from feedback

- _quarto.yml
- handbook/hackathon-facilitation.md
- handbook/index.md
---
:mag: Preview: https://geojupyter--74.org.readthedocs.build/en/74/
> Add hackathon facilitation guide

- cng-2025.md
---
:mag: Preview: https://geojupyter--77.org.readthedocs.build/en/77/
> Add link to slides website

- pixi.lock
- pixi.toml
---
:mag: Preview: https://geojupyter--85.org.readthedocs.build/en/85/
> Add Windows platform and update lockfile

- about.md
---
:mag: Preview: https://geojupyter--86.org.readthedocs.build/en/86/
> Adjust "About" intro text

- .github/workflows/deploy-to-gh-pages.yml
---
:mag: Preview: https://geojupyter--95.org.readthedocs.build/en/95/
> Update setup-pixi workflow

- _quarto.yml
---
:mag: Preview: https://geojupyter--100.org.readthedocs.build/en/100/
> Update navigation to link out to auxillary sites

- about.md
---
:mag: Preview: https://geojupyter--109.org.readthedocs.build/en/109/
> Recognize Simula's community membership
